export { default as Home } from './home/Home'
export { default as Toolbar } from './toolbar/Toolbar'
export { default as Coloring } from './coloring/Coloring'
export { default as Maze } from './maze/Maze'
export { default as Puzzle } from './puzzle/Puzzle'
export { default as Shadow } from './shadow/Shadow'
export { default as ShapeNumber } from './shapeNumber/ShapeNumber'
export { default as Similarities } from './similarities/Similarities'